[target.thumbv7em-none-eabihf]
runner = 'probe-run --chip STM32F412RETx'
rustflags = [
    '-C',
    'link-arg=-Tlink.x',
]

[toolchain]
channel = 'stable'

[build]
target = 'thumbv7em-none-eabihf'

[env]
DEFMT_LOG = 'info'
